version: "3.9"

services:
  gajiku:
    build: .
    container_name: gajiku
    labels:
      - traefik.backend=gajiku-backend
      - traefik.frontend.rule=Host:api-gajiku.techack.id
      - traefik.docker.network=web
      - traefik.port=80
    volumes:
      - .:/app
    networks:
      - web
    restart: always

networks:
  web:
    external: true