version: "3.8"

services:
  app:
    build: mpapi
    env_file:
      - .env
    ports:
      - "8000:8000"


  database:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"

