"""empty message

Revision ID: 1136740ec74e
Revises: cbd73265a9cc
Create Date: 2022-04-26 07:47:21.751330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1136740ec74e'
down_revision = 'cbd73265a9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_gaji_kawin', sa.Column('tunjangan_is', sa.Float(), nullable=False))
    op.add_column('set_gaji_kawin', sa.Column('tunjangan_anak', sa.Float(), nullable=False))
    op.add_column('set_gaji_kawin', sa.Column('tunjangan_beras', sa.Float(), nullable=False))
    op.add_column('set_gaji_kawin', sa.Column('besaran_ptkp', sa.Float(), nullable=True))
    op.add_column('set_gaji_kawin', sa.Column('jenis_besaran_ptkp', sa.Enum('persentase', 'spesifik'), nullable=False))
    op.drop_index('ix_set_gaji_kawin_besaran', table_name='set_gaji_kawin')
    op.drop_index('ix_set_gaji_kawin_jenis_besaran', table_name='set_gaji_kawin')
    op.create_index(op.f('ix_set_gaji_kawin_besaran_ptkp'), 'set_gaji_kawin', ['besaran_ptkp'], unique=False)
    op.create_index(op.f('ix_set_gaji_kawin_jenis_besaran_ptkp'), 'set_gaji_kawin', ['jenis_besaran_ptkp'], unique=False)
    op.create_index(op.f('ix_set_gaji_kawin_tunjangan_anak'), 'set_gaji_kawin', ['tunjangan_anak'], unique=False)
    op.create_index(op.f('ix_set_gaji_kawin_tunjangan_beras'), 'set_gaji_kawin', ['tunjangan_beras'], unique=False)
    op.create_index(op.f('ix_set_gaji_kawin_tunjangan_is'), 'set_gaji_kawin', ['tunjangan_is'], unique=False)
    op.drop_column('set_gaji_kawin', 'besaran')
    op.drop_column('set_gaji_kawin', 'jenis_besaran')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_gaji_kawin', sa.Column('jenis_besaran', mysql.ENUM('persentase', 'spesifik'), nullable=False))
    op.add_column('set_gaji_kawin', sa.Column('besaran', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_set_gaji_kawin_tunjangan_is'), table_name='set_gaji_kawin')
    op.drop_index(op.f('ix_set_gaji_kawin_tunjangan_beras'), table_name='set_gaji_kawin')
    op.drop_index(op.f('ix_set_gaji_kawin_tunjangan_anak'), table_name='set_gaji_kawin')
    op.drop_index(op.f('ix_set_gaji_kawin_jenis_besaran_ptkp'), table_name='set_gaji_kawin')
    op.drop_index(op.f('ix_set_gaji_kawin_besaran_ptkp'), table_name='set_gaji_kawin')
    op.create_index('ix_set_gaji_kawin_jenis_besaran', 'set_gaji_kawin', ['jenis_besaran'], unique=False)
    op.create_index('ix_set_gaji_kawin_besaran', 'set_gaji_kawin', ['besaran'], unique=False)
    op.drop_column('set_gaji_kawin', 'jenis_besaran_ptkp')
    op.drop_column('set_gaji_kawin', 'besaran_ptkp')
    op.drop_column('set_gaji_kawin', 'tunjangan_beras')
    op.drop_column('set_gaji_kawin', 'tunjangan_anak')
    op.drop_column('set_gaji_kawin', 'tunjangan_is')
    # ### end Alembic commands ###
