"""empty message

Revision ID: bddb94b47a2a
Revises: 0ffe2940bbce
Create Date: 2022-04-25 15:16:26.833516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddb94b47a2a'
down_revision = '0ffe2940bbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_gaji_jabatan', sa.Column('jabatan', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_set_gaji_jabatan_jabatan'), 'set_gaji_jabatan', ['jabatan'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_gaji_jabatan_jabatan'), table_name='set_gaji_jabatan')
    op.drop_column('set_gaji_jabatan', 'jabatan')
    # ### end Alembic commands ###
