"""empty message

Revision ID: cbd73265a9cc
Revises: bddb94b47a2a
Create Date: 2022-04-25 15:43:30.603964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd73265a9cc'
down_revision = 'bddb94b47a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_gaji_jabatan', sa.Column('kode', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_set_gaji_jabatan_kode'), 'set_gaji_jabatan', ['kode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_gaji_jabatan_kode'), table_name='set_gaji_jabatan')
    op.drop_column('set_gaji_jabatan', 'kode')
    # ### end Alembic commands ###
