"""empty message

Revision ID: e175c7866e45
Revises: 1136740ec74e
Create Date: 2022-04-26 08:09:15.955991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e175c7866e45'
down_revision = '1136740ec74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
