"""empty message

Revision ID: f3c5148ea0e1
Revises: 5bb9d5e30fc9
Create Date: 2022-04-28 15:09:35.608558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3c5148ea0e1'
down_revision = '5bb9d5e30fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_gaji_bpjs', sa.Column('kelas', sa.String(length=50), nullable=False))
    op.drop_index('ix_set_gaji_bpjs_kode', table_name='set_gaji_bpjs')
    op.create_index(op.f('ix_set_gaji_bpjs_kelas'), 'set_gaji_bpjs', ['kelas'], unique=False)
    op.drop_column('set_gaji_bpjs', 'kode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_gaji_bpjs', sa.Column('kode', mysql.VARCHAR(length=50), nullable=False))
    op.drop_index(op.f('ix_set_gaji_bpjs_kelas'), table_name='set_gaji_bpjs')
    op.create_index('ix_set_gaji_bpjs_kode', 'set_gaji_bpjs', ['kode'], unique=False)
    op.drop_column('set_gaji_bpjs', 'kelas')
    # ### end Alembic commands ###
